package heartssystem;

public class EnterNamesGUI extends BasicGUI {
    private static EnterNamesGUI instance = null;
    HeartsGUI heartsGUI;
    
    private EnterNamesGUI(HeartsEngine e, HeartsGUI gui) {
        super(e);
        heartsGUI = gui;
        initComponents();
    }
    
    public static EnterNamesGUI getInstance(HeartsEngine e, HeartsGUI gui) {
        if (instance == null) {
            instance = new EnterNamesGUI(e, gui);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1TextBox = new javax.swing.JTextField();
        player2TextBox = new javax.swing.JTextField();
        player3TextBox = new javax.swing.JTextField();
        player4TextBox = new javax.swing.JTextField();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player3Label = new javax.swing.JLabel();
        player4Label = new javax.swing.JLabel();
        pleaseEnterLabel = new javax.swing.JLabel();
        startBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        player1TextBox.setText("Player 1");

        player2TextBox.setText("Player 2");

        player3TextBox.setText("Player 3");

        player4TextBox.setText("Player 4");

        player1Label.setText("Player 1:");

        player2Label.setText("Player 2:");

        player3Label.setText("Player 3:");

        player4Label.setText("Player 4:");

        pleaseEnterLabel.setText("Please enter players names:");

        startBttn.setText("Start");
        startBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pleaseEnterLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player1Label)
                                    .addComponent(player2Label)
                                    .addComponent(player3Label)
                                    .addComponent(player4Label))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player1TextBox)
                                    .addComponent(player2TextBox)
                                    .addComponent(player3TextBox)
                                    .addComponent(player4TextBox)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(startBttn)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pleaseEnterLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label)
                    .addComponent(player1TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Label)
                    .addComponent(player2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player3Label)
                    .addComponent(player3TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4Label)
                    .addComponent(player4TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(startBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBttnActionPerformed
        updatePlayerNames();
        heartsGUI.updateNames();
        this.dispose();
    }//GEN-LAST:event_startBttnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       updatePlayerNames();
       heartsGUI.updateNames();
    }//GEN-LAST:event_formWindowClosed

    private void updatePlayerNames() {
        if (player1TextBox.getText().length() > 0) { // only updates if text box isn't empty, else uses default name originally set
            getEngine().getPlayer(0).setName(player1TextBox.getText());
        }
        if (player2TextBox.getText().length() > 0) {
            getEngine().getPlayer(1).setName(player2TextBox.getText());
        }
        if (player3TextBox.getText().length() > 0) {
            getEngine().getPlayer(2).setName(player3TextBox.getText());
        }
        if (player4TextBox.getText().length() > 0) {
            getEngine().getPlayer(3).setName(player4TextBox.getText());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterNamesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterNamesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterNamesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterNamesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1TextBox;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2TextBox;
    private javax.swing.JLabel player3Label;
    private javax.swing.JTextField player3TextBox;
    private javax.swing.JLabel player4Label;
    private javax.swing.JTextField player4TextBox;
    private javax.swing.JLabel pleaseEnterLabel;
    private javax.swing.JButton startBttn;
    // End of variables declaration//GEN-END:variables
}
