package heartssystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author J.Appallonia
 */
public class Hearts extends javax.swing.JFrame {
    private Player curPlayer;
    private final ImageIcon[][] cardFiles = new ImageIcon[4][13];
    private final String[] suits = {"Clubs","Diamonds","Spades","Hearts"};
    private final JLabel[] cardsInHand = new JLabel[13];
    
    public Hearts() {
        swapBttn.setVisible(false);
        for (int suit = 0; suit < 4; suit++) {
            for (int face = 0; face < 13; face++) {
                cardFiles[suit][face] = new ImageIcon(getClass().
                        getResource("/cardImages/"+suits[suit]+Integer.toString(face+1)+".png"));
            }
        }
        mouseHandler mHand = new mouseHandler();
        cardsInHand[0] = card1;
        cardsInHand[1] = card2;
        cardsInHand[2] = card3;
        cardsInHand[3] = card4;
        cardsInHand[4] = card5;
        cardsInHand[5] = card6;
        cardsInHand[6] = card7;
        cardsInHand[7] = card8;
        cardsInHand[8] = card9;
        cardsInHand[9] = card10;
        cardsInHand[10] = card11;
        cardsInHand[11] = card12;
        cardsInHand[12] = card13;
        card1.addMouseListener(mHand);
        card2.addMouseListener(mHand);
        card3.addMouseListener(mHand);
        card4.addMouseListener(mHand);
        card5.addMouseListener(mHand);
        card6.addMouseListener(mHand);
        card7.addMouseListener(mHand);
        card8.addMouseListener(mHand);
        card9.addMouseListener(mHand);
        card10.addMouseListener(mHand);
        card11.addMouseListener(mHand);
        card12.addMouseListener(mHand);
        card13.addMouseListener(mHand);
        initComponents();
    }
    
    public void update() {
        Card thisC;
        for (int i = 0; i < 13; i++)
        {
            thisC = curPlayer.getHand().getCard(i+1);
            cardsInHand[i].setIcon(cardFiles[thisC.getSuit()][thisC.getFace()]);
            curPlayer.getHand().getCard(1).setSelected(true);
            cardsInHand[0].setLocation(cardsInHand[0].getX(), cardsInHand[0].getY()-20);
        }
    }
    
    public void hideSwapButton() {
        swapBttn.setVisible(false);
    }
    
    public void showSwapButton() {
        swapBttn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        swapBttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new javax.swing.JLabel();
        card2 = new javax.swing.JLabel();
        card3 = new javax.swing.JLabel();
        card4 = new javax.swing.JLabel();
        card5 = new javax.swing.JLabel();
        card6 = new javax.swing.JLabel();
        card7 = new javax.swing.JLabel();
        card8 = new javax.swing.JLabel();
        card9 = new javax.swing.JLabel();
        card10 = new javax.swing.JLabel();
        card11 = new javax.swing.JLabel();
        card12 = new javax.swing.JLabel();
        card13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        swapBttn.setText("Swap");
        swapBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwapCards(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(63, 91));
        jLabel3.setMinimumSize(new java.awt.Dimension(63, 91));
        jLabel3.setPreferredSize(new java.awt.Dimension(63, 91));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardImages/Clubs1.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setMaximumSize(new java.awt.Dimension(63, 91));
        jLabel4.setMinimumSize(new java.awt.Dimension(63, 91));
        jLabel4.setPreferredSize(new java.awt.Dimension(63, 91));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("jLabel1");
        jLabel6.setMaximumSize(new java.awt.Dimension(63, 91));
        jLabel6.setMinimumSize(new java.awt.Dimension(63, 91));
        jLabel6.setPreferredSize(new java.awt.Dimension(63, 91));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("jLabel1");
        jLabel7.setMaximumSize(new java.awt.Dimension(63, 91));
        jLabel7.setMinimumSize(new java.awt.Dimension(63, 91));
        jLabel7.setPreferredSize(new java.awt.Dimension(63, 91));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(514, 91));

        card1.setBackground(new java.awt.Color(0, 0, 0));
        card1.setText("jLabel1");
        card1.setAlignmentX(0.4F);
        card1.setMaximumSize(new java.awt.Dimension(63, 91));
        card1.setMinimumSize(new java.awt.Dimension(63, 91));
        card1.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card1);
        card1.setBounds(0, 0, 63, 91);

        card2.setBackground(new java.awt.Color(0, 0, 0));
        card2.setText("jLabel1");
        card2.setAlignmentX(0.6F);
        card2.setMaximumSize(new java.awt.Dimension(63, 91));
        card2.setMinimumSize(new java.awt.Dimension(63, 91));
        card2.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card2);
        card2.setBounds(20, 0, 63, 91);

        card3.setBackground(new java.awt.Color(0, 0, 0));
        card3.setText("jLabel1");
        card3.setAlignmentX(0.8F);
        card3.setMaximumSize(new java.awt.Dimension(63, 91));
        card3.setMinimumSize(new java.awt.Dimension(63, 91));
        card3.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card3);
        card3.setBounds(40, 0, 63, 91);

        card4.setBackground(new java.awt.Color(0, 0, 0));
        card4.setText("jLabel1");
        card4.setAlignmentX(1.0F);
        card4.setMaximumSize(new java.awt.Dimension(63, 91));
        card4.setMinimumSize(new java.awt.Dimension(63, 91));
        card4.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card4);
        card4.setBounds(60, 0, 63, 91);

        card5.setBackground(new java.awt.Color(0, 0, 0));
        card5.setText("jLabel1");
        card5.setAlignmentX(1.2F);
        card5.setMaximumSize(new java.awt.Dimension(63, 91));
        card5.setMinimumSize(new java.awt.Dimension(63, 91));
        card5.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card5);
        card5.setBounds(80, 0, 63, 91);

        card6.setBackground(new java.awt.Color(0, 0, 0));
        card6.setText("jLabel1");
        card6.setAlignmentX(1.4F);
        card6.setMaximumSize(new java.awt.Dimension(63, 91));
        card6.setMinimumSize(new java.awt.Dimension(63, 91));
        card6.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card6);
        card6.setBounds(100, 0, 63, 91);

        card7.setBackground(new java.awt.Color(0, 0, 0));
        card7.setText("jLabel1");
        card7.setAlignmentX(1.6F);
        card7.setMaximumSize(new java.awt.Dimension(63, 91));
        card7.setMinimumSize(new java.awt.Dimension(63, 91));
        card7.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card7);
        card7.setBounds(120, 0, 63, 91);

        card8.setBackground(new java.awt.Color(0, 0, 0));
        card8.setText("jLabel1");
        card8.setAlignmentX(1.8F);
        card8.setMaximumSize(new java.awt.Dimension(63, 91));
        card8.setMinimumSize(new java.awt.Dimension(63, 91));
        card8.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card8);
        card8.setBounds(140, 0, 63, 91);

        card9.setBackground(new java.awt.Color(0, 0, 0));
        card9.setText("jLabel1");
        card9.setAlignmentX(2.0F);
        card9.setMaximumSize(new java.awt.Dimension(63, 91));
        card9.setMinimumSize(new java.awt.Dimension(63, 91));
        card9.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card9);
        card9.setBounds(160, 0, 63, 91);

        card10.setBackground(new java.awt.Color(0, 0, 0));
        card10.setText("jLabel1");
        card10.setAlignmentX(2.2F);
        card10.setMaximumSize(new java.awt.Dimension(63, 91));
        card10.setMinimumSize(new java.awt.Dimension(63, 91));
        card10.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card10);
        card10.setBounds(180, 0, 63, 91);

        card11.setBackground(new java.awt.Color(0, 0, 0));
        card11.setText("jLabel1");
        card11.setAlignmentX(2.6F);
        card11.setMaximumSize(new java.awt.Dimension(63, 91));
        card11.setMinimumSize(new java.awt.Dimension(63, 91));
        card11.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card11);
        card11.setBounds(200, 0, 63, 91);

        card12.setBackground(new java.awt.Color(0, 0, 0));
        card12.setText("jLabel1");
        card12.setMaximumSize(new java.awt.Dimension(63, 91));
        card12.setMinimumSize(new java.awt.Dimension(63, 91));
        card12.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card12);
        card12.setBounds(220, 0, 63, 91);

        card13.setBackground(new java.awt.Color(0, 0, 0));
        card13.setText("jLabel1");
        card13.setAlignmentX(0.2F);
        card13.setMaximumSize(new java.awt.Dimension(63, 91));
        card13.setMinimumSize(new java.awt.Dimension(63, 91));
        card13.setPreferredSize(new java.awt.Dimension(63, 91));
        jLayeredPane1.add(card13);
        card13.setBounds(240, 0, 63, 91);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(swapBttn)
                                .addGap(87, 87, 87)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(swapBttn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SwapCards(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwapCards
        //curPlayer.passCard();
    }//GEN-LAST:event_SwapCards

    private class mouseHandler extends MouseAdapter {
        @Override
        public void mouseClicked(MouseEvent e)
        {
            int num = Integer.parseInt(e.getSource().toString().substring(4));
            if (e.getClickCount() >= 2)
            {
                curPlayer.playCard(num);
            } else {
                System.out.printf("%d",num);
                JLabel thisCard = (JLabel)e.getSource();
                if (curPlayer.getHand().getCard(num).getSelected()) { // card is selected
                    curPlayer.getHand().getCard(num).setSelected(false);
                    thisCard.setLocation(thisCard.getX(), thisCard.getY()+20);
                } else {
                    // card is not selected
                    curPlayer.getHand().getCard(num).setSelected(true);
                    thisCard.setLocation(thisCard.getX(), thisCard.getY()-20);
                }
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hearts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hearts().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card1;
    private javax.swing.JLabel card10;
    private javax.swing.JLabel card11;
    private javax.swing.JLabel card12;
    private javax.swing.JLabel card13;
    private javax.swing.JLabel card2;
    private javax.swing.JLabel card3;
    private javax.swing.JLabel card4;
    private javax.swing.JLabel card5;
    private javax.swing.JLabel card6;
    private javax.swing.JLabel card7;
    private javax.swing.JLabel card8;
    private javax.swing.JLabel card9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton swapBttn;
    // End of variables declaration//GEN-END:variables
}
