/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heartssystem;

/**
 *
 * @author Revenant Penguin
 */
public class StatsGUI extends BasicGUI {

    public StatsGUI(HeartsEngine e) {
        super(e);
        initComponents();
        Player1GamesWon.setText(Integer.toString(getEngine().getSession().getWins(0)));
        Player1MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(0)));
        Player2GamesWon.setText(Integer.toString(getEngine().getSession().getWins(1)));
        Player2MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(1)));
        Player3GamesWon.setText(Integer.toString(getEngine().getSession().getWins(2)));
        Player3MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(2)));
        Player4GamesWon.setText(Integer.toString(getEngine().getSession().getWins(3)));
        Player4MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(3)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Player1GamesWon = new javax.swing.JLabel();
        Player1MoonsShot = new javax.swing.JLabel();
        Player2GamesWon = new javax.swing.JLabel();
        Player3GamesWon = new javax.swing.JLabel();
        Player4GamesWon = new javax.swing.JLabel();
        Player2MoonsShot = new javax.swing.JLabel();
        Player3MoonsShot = new javax.swing.JLabel();
        Player4MoonsShot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Player 1:");

        jLabel2.setText("Player 2:");

        jLabel3.setText("Player 3:");

        jLabel4.setText("Player 4:");

        jLabel5.setText("Games Won:");

        jLabel6.setText("Moons Shot");

        Player1GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1GamesWon.setText("0");

        Player1MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1MoonsShot.setText("0");

        Player2GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2GamesWon.setText("0");

        Player3GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player3GamesWon.setText("0");

        Player4GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player4GamesWon.setText("0");

        Player2MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2MoonsShot.setText("0");

        Player3MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player3MoonsShot.setText("0");

        Player4MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player4MoonsShot.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Player2GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Player1GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Player4GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Player3GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Player1MoonsShot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Player2MoonsShot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Player3MoonsShot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Player4MoonsShot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Player1GamesWon)
                    .addComponent(Player1MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Player2GamesWon)
                    .addComponent(Player2MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Player3GamesWon)
                    .addComponent(Player3MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Player4GamesWon)
                    .addComponent(Player4MoonsShot))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Player1GamesWon;
    private javax.swing.JLabel Player1MoonsShot;
    private javax.swing.JLabel Player2GamesWon;
    private javax.swing.JLabel Player2MoonsShot;
    private javax.swing.JLabel Player3GamesWon;
    private javax.swing.JLabel Player3MoonsShot;
    private javax.swing.JLabel Player4GamesWon;
    private javax.swing.JLabel Player4MoonsShot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
