package heartssystem;

public class StatsGUI extends BasicGUI {
    public StatsGUI(HeartsEngine e) {
        super(e);
        initComponents();
        player1Label.setText(getEngine().getPlayer(0).getName());
        player1GamesWon.setText(Integer.toString(getEngine().getSession().getWins(0)));
        player1MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(0)));
        player2Label.setText(getEngine().getPlayer(1).getName());
        player2GamesWon.setText(Integer.toString(getEngine().getSession().getWins(1)));
        player2MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(1)));
        player3Label.setText(getEngine().getPlayer(2).getName());
        player3GamesWon.setText(Integer.toString(getEngine().getSession().getWins(2)));
        player3MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(2)));
        player4Label.setText(getEngine().getPlayer(3).getName());
        player4GamesWon.setText(Integer.toString(getEngine().getSession().getWins(3)));
        player4MoonsShot.setText(Integer.toString(getEngine().getSession().getMoons(3)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player3Label = new javax.swing.JLabel();
        player4Label = new javax.swing.JLabel();
        gamesWonLabel = new javax.swing.JLabel();
        moonsShotLabel = new javax.swing.JLabel();
        player1GamesWon = new javax.swing.JLabel();
        player1MoonsShot = new javax.swing.JLabel();
        player2GamesWon = new javax.swing.JLabel();
        player3GamesWon = new javax.swing.JLabel();
        player4GamesWon = new javax.swing.JLabel();
        player2MoonsShot = new javax.swing.JLabel();
        player3MoonsShot = new javax.swing.JLabel();
        player4MoonsShot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        player1Label.setText("Player 1:");

        player2Label.setText("Player 2:");

        player3Label.setText("Player 3:");

        player4Label.setText("Player 4:");

        gamesWonLabel.setText("Games Won:");

        moonsShotLabel.setText("Moons Shot");

        player1GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1GamesWon.setText("0");

        player1MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1MoonsShot.setText("0");

        player2GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2GamesWon.setText("0");

        player3GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3GamesWon.setText("0");

        player4GamesWon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player4GamesWon.setText("0");

        player2MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2MoonsShot.setText("0");

        player3MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3MoonsShot.setText("0");

        player4MoonsShot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player4MoonsShot.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player3Label)
                    .addComponent(player4Label)
                    .addComponent(player2Label)
                    .addComponent(player1Label))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(player2GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player1GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player4GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player3GamesWon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gamesWonLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moonsShotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player1MoonsShot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player2MoonsShot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player3MoonsShot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player4MoonsShot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesWonLabel)
                    .addComponent(moonsShotLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label)
                    .addComponent(player1GamesWon)
                    .addComponent(player1MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Label)
                    .addComponent(player2GamesWon)
                    .addComponent(player2MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player3Label)
                    .addComponent(player3GamesWon)
                    .addComponent(player3MoonsShot))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4Label)
                    .addComponent(player4GamesWon)
                    .addComponent(player4MoonsShot))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gamesWonLabel;
    private javax.swing.JLabel moonsShotLabel;
    private javax.swing.JLabel player1GamesWon;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player1MoonsShot;
    private javax.swing.JLabel player2GamesWon;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel player2MoonsShot;
    private javax.swing.JLabel player3GamesWon;
    private javax.swing.JLabel player3Label;
    private javax.swing.JLabel player3MoonsShot;
    private javax.swing.JLabel player4GamesWon;
    private javax.swing.JLabel player4Label;
    private javax.swing.JLabel player4MoonsShot;
    // End of variables declaration//GEN-END:variables
}
